name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython

      - name: Pre-setup python-for-android
        run: |
          # Qovluğu birbaşa özümüz yaradırıq ki, Buildozer onu axtaranda tapsın
          mkdir -p .buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: .buildozer/logs/
